obsforge:
  PSLOT: obsforge
  HOMEobsforge: /work2/noaa/da/mchoi3/temp/obsForge
  SDATE: 202503141800
  EDATE: 202503150000
  COMROOT: /work2/noaa/da/mchoi3/temp/test_obsForge/COMROOT
  DCOMROOT: /work2/noaa/da/common/lfs/h1/ops/prod/dcom
  DATAROOT: /work2/noaa/da/mchoi3/temp/test_obsForge/RUNDIRS
  SCHEDULER: slurm
  ACCOUNT: da-cpu
  QUEUE: debug
  PARTITION: hercules
  KEEPDATA: NO
  assim_freq: 6

aoddump:
  provider: VIIRSAOD
  platforms: ['npp', 'n20', 'n21']
  thinning_threshold: 0
  channel: 4
  preqc: 2
  WALLTIME_AOD_DUMP: '00:10:00'
  TASK_GEOM_AOD_DUMP: '1:ppn=1:tpp=1'
  MEMORY_AOD_DUMP: 96GB

marinedump:
  providers:
    ghrsst:
      list:
        - sst_avhrrf_ma_l3u
        - sst_avhrrf_mb_l3u
      qc config:
        min: -2.0
        max: 45.0
        stride: 15
        min number of obs: 10
    rads:
      list:
        - rads_adt_3a
        - rads_adt_3b
      qc config:
        min: -2.0
        max: 3.0
        error ratio: 1.0
    nesdis_amsr2:
      list:
        - icec_amsr2_north
        - icec_amsr2_south
      qc config:
        min: 0.0
        max: 1.0
    nesdis_mirs:
      list:
        - icec_amsu_ma1_l2
        - icec_atms_n20_l2
        - icec_atms_n21_l2
        - icec_atms_npp_l2
        - icec_gmi_gpm_l2
      qc config:
        min: 0.0
        max: 1.0
    smap:
      list:
        - sss_smap_l2
      qc config:
        min: 0.1
        max: 40.0
    smos:
      list:
        - sss_smos_l2
      qc config:
        min: 0.1
        max: 40.0

  WALLTIME_MARINE_DUMP: '00:10:00'
  TASK_GEOM_MARINE_DUMP: '1:ppn=20:tpp=2'
  MEMORY_MARINE_DUMP: 32GB
