obsforge:
  PSLOT: obsforge
  HOMEobsforge: /lfs/h2/emc/da/noscrub/Hyundeok.Choi/obsForge_reg 
  SDATE: 202606010000
  EDATE: 202612311800
  COMROOT: /lfs/h2/emc/da/noscrub/Hyundeok.Choi/obsForge_reg/COMROOT
  DCOMROOT: /lfs/h1/ops/prod/dcom/
  DATAROOT: /lfs/h2/emc/da/noscrub/Hyundeok.Choi/obsForge_reg/RUNDIRS 
  OBSPROC_COMROOT: /lfs/h1/ops/prod/com/obsproc/v1.2
  SCHEDULER: pbspro
  ACCOUNT: GFS-DEV
  QUEUE: dev
  PARTITION: dev 
  KEEPDATA: YES
  assim_freq: 6
  ocean_basin: "/lfs/h2/emc/da/noscrub/common/validation/RECCAP2_region_masks_all_v20221025.nc"
  MPI_LAUNCHER: mpiexec

atmosbufrdump:
  WALLTIME_ATMOS_BUFR_DUMP: '00:20:00'
  TASK_GEOM_ATMOS_BUFR_DUMP: '1:ppn=80:tpp=1'
  MEMORY_ATMOS_BUFR_DUMP: 256GB

gsitoioda:
  WALLTIME_GSI_TO_IODA: '00:20:00'
  TASK_GEOM_GSI_TO_IODA: '1:ppn=80:tpp=1'
  MEMORY_GSI_TO_IODA: 256GB

stageout:
  WALLTIME_STAGE_OUTPUT: '00:10:00'
  TASK_GEOM_STAGE_OUTPUT: '1:ppn=1:tpp=1'
  MEMORY_STAGE_OUTPUT: 32GB

