obsforge:
  PSLOT: obsforge
  HOMEobsforge: /scratch3/NCEPDEV/stmp/Cory.R.Martin/sep2025/ObsForge/obsforge
  SDATE: 202506011800
  EDATE: 202506020000
  COMROOT: /scratch4/NCEPDEV/stmp/Cory.R.Martin/ObsForge/com
  DCOMROOT: /scratch1/NCEPDEV/da/common/realtime_sample/lfs/h1/ops/prod/dcom
  DATAROOT: /scratch4/NCEPDEV/stmp/Cory.R.Martin/ObsForge/RUNDIRS
  OBSPROC_COMROOT: /scratch3/NCEPDEV/global/role.glopara/dump/
  SCHEDULER: slurm
  ACCOUNT: da-cpu
  QUEUE: debug
  PARTITION: hera
  KEEPDATA: NO
  assim_freq: 6
  DMPDIR: /scratch1/NCEPDEV/da/common/
  ocean_basin: "/scratch3/NCEPDEV/da/common/validation/RECCAP2_region_masks_all_v20221025.nc"

atmosbufrdump:
  observations:
    prepbufr_adpsfc:
      method: bufr2netcdf
      input file: prepbufr
      output file: prepbufr_adpsfc.nc
      mapping file: prepbufr_adpsfc.yaml
  WALLTIME_ATMOS_BUFR_DUMP: '00:10:00'
  TASK_GEOM_ATMOS_BUFR_DUMP: '1:ppn=1:tpp=1'
  MEMORY_ATMOS_BUFR_DUMP: 96GB

aoddump:
  provider: VIIRSAOD
  platforms: ['npp', 'n20', 'n21'] # note j01==n20
  thinning_threshold: 0.9931
  channel: 4
  preqc: 2
  WALLTIME_AOD_DUMP: '00:10:00'
  TASK_GEOM_AOD_DUMP: '1:ppn=1:tpp=1'
  MEMORY_AOD_DUMP: 96GB

marinedump:
  providers:
    ghrsst:
      list:
        - sst_viirs_n21_l3u
        - sst_viirs_n20_l3u
        - sst_viirs_npp_l3u
        - sst_avhrrf_ma_l3u
        - sst_avhrrf_mb_l3u
        - sst_avhrrf_mc_l3u
        - sst_ahi_h08_l3c
        - sst_abi_g17_l3c
        - sst_abi_g16_l3c
      qc config:
        min: -2.0
        max: 45.0
        stride: 15
        min number of obs: 10
    rads:
      list:
        - rads_adt_3a
        - rads_adt_3b
        - rads_adt_6a
        - rads_adt_c2
        - rads_adt_j2
        - rads_adt_j3
        - rads_adt_sa
        - rads_adt_sw        
        - rads_adt_3a
        - rads_adt_3b
      qc config:
        min: -2.0
        max: 3.0
        error ratio: 1.0
    nesdis_amsr2:
      list:
        - icec_amsr2_north
        - icec_amsr2_south
      qc config:
        min: 0.0
        max: 1.0
    nesdis_mirs:
      list:
        - icec_amsu_ma1_l2
        - icec_atms_n20_l2
        - icec_atms_n21_l2
        - icec_atms_npp_l2
#        - icec_gmi_gpm_l2
      qc config:
        min: 0.0
        max: 1.0
    nesdis_jpssrr:
      list:
        - icec_viirs_j01_l2
        - icec_viirs_n21_l2
        - icec_viirs_npp_l2
      qc config:
        min: 0.0
        max: 1.0
    smap:
      list:
        - sss_smap_l2
      qc config:
        min: 0.1
        max: 40.0
    smos:
      list:
        - sss_smos_l2
      qc config:
        min: 0.1
        max: 40.0

  WALLTIME_MARINE_DUMP: '00:10:00'
  TASK_GEOM_MARINE_DUMP: '1:ppn=20:tpp=2'
  MEMORY_MARINE_DUMP: 32GB


marinebufrdump:

  WALLTIME_MARINE_BUFR_DUMP: '00:10:00'
  TASK_GEOM_MARINE_BUFR_DUMP: '1:ppn=1:tpp=1'
  MEMORY_MARINE_BUFR_DUMP: 32GB
