obsforge:
  PSLOT: realtimeobs_testing
  HOMEobsforge: /work/noaa/da/gvernier/runs/obsForge
  SDATE: 202503141800
  EDATE: 202503150000
  COMROOT: /work/noaa/da/gvernier/runs/test_obsforge/COMROOT
  DCOMROOT: /work2/noaa/da/common/lfs/h1/ops/prod/dcom
  DATAROOT: /work/noaa/da/gvernier/runs/test_obsforge/RUNDIRS
  SCHEDULER: slurm
  ACCOUNT: da-cpu
  QUEUE: debug
  PARTITION: orion
  KEEPDATA: NO
  assim_freq: 6

aoddump:
  provider: VIIRSAOD
  platforms: ['npp', 'n20', 'n21']
  thinning_threshold: 0
  channel: 4
  preqc: 2
  WALLTIME_AOD_DUMP: '00:10:00'
  TASK_GEOM_AOD_DUMP: '1:ppn=1:tpp=1'
  MEMORY_AOD_DUMP: 96GB

marinedump:
  providers:
    ghrsst:
      list:
        #- sst_viirs_n21_l3u
        #- sst_viirs_n20_l3u
        #- sst_viirs_npp_l3u
        #- sst_avhrrf_ma_l3u
        #- sst_avhrrf_mb_l3u
        - sst_avhrrf_mc_l3u
        #- sst_ahi_h08_l3c
        #- sst_abi_g17_l3c
        #- sst_abi_g16_l3c
      qc config:
        min: -2.0
        max: 45.0
        stride: 15
        min number of obs: 10
    rads:
      list:
        - rads_adt_3a
        - rads_adt_3b
        - rads_adt_6a
        - rads_adt_c2
        - rads_adt_j2
        - rads_adt_j3
        - rads_adt_sa
        - rads_adt_sw
      qc config:
        min: -2.0
        max: 3.0
        error ratio: 1.0

  WALLTIME_MARINE_DUMP: '00:10:00'
  TASK_GEOM_MARINE_DUMP: '1:ppn=20:tpp=2'
  MEMORY_MARINE_DUMP: 32GB
