#! /usr/bin/env bash

source "${HOMEobsforge}/ush/preamble.sh"
source "${HOMEobsforge}/ush/jjob_header.sh"

##############################################
# Set variables used in the script
##############################################
obsforge_ver=${obsforge_ver:-v1.0}
_combase=$(compath.py "${envir}/${NET}/${obsforge_ver}" 2>/dev/null) || _combase="${COMROOT}"
export COMOUT_OBSFORGE_ATMOS_GSI_OBS="${_combase}/${RUN}.${PDY}/${cyc}/atmos_gsi"

##############################################
# Begin JOB SPECIFIC work
##############################################

###############################################################
# Run relevant script

EXSCRIPT=${GSITOIODAPY:-${HOMEobsforge}/scripts/exobsforge_global_gsi_to_ioda.py}
${EXSCRIPT}
status=$?
if [[ ${status} -ne 0 ]]; then
    exit "${status}"
fi


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
