on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker Image
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: docker-${{ runner.os }}-jcsda/docker-gnu-openmpi-dev
          restore-keys: |
            docker-${{ runner.os }}-

      - name: Load Cached Docker Image
        run: |
          mkdir -p /tmp/.docker-cache
          if [ -f /tmp/.docker-cache/jcsda/docker-gnu-openmpi-dev.tar ]; then
            docker load -i /tmp/.docker-cache/jcsda/docker-gnu-openmpi-dev.tar || true
          fi

      - name: Pull or Use Cached Image
        run: |
          docker pull jcsda/docker-gnu-openmpi-dev:latest || true
          docker save -o /tmp/.docker-cache/jcsda/docker-gnu-openmpi-dev.tar jcsda/docker-gnu-openmpi-dev:latest

